apiVersion: v1
kind: Service
metadata:
  name: snayder-vicente-42-fe-service
  namespace: snayder-vicente-42-namespace
spec:
  type: NodePort
  ports:
  - port: 30043
    targetPort: 80
    nodePort: 30043
  selector:
    app: snayder-vicente-42-fe-deployment